---
# tasks file for ansible-tfenv
# Pre-reqs
- name: Install git
  package: 
    name: "git"

- name: Create tfenv directory
  file: path=/opt/tfenv state=directory mode="a+rw"

- name: Get tfenv
  ansible.builtin.git:
    repo: 'https://github.com/tfutils/tfenv.git'
    dest: /opt/tfenv

- name: Verify tfenv exists
  stat: path=/opt/tfenv/bin/tfenv
  register: tfenv_stat

- name: Configure tfenv on system bin.
  file:
    src: "/opt/tfenv/bin/tfenv"
    dest: "/usr/bin/tfenv"
    state: link
  when: tfenv_stat.stat.exists

- name: Configure tfenv on system sbin.
  file:
    src: "/opt/tfenv/bin/tfenv"
    dest: "/usr/sbin/tfenv"
    state: link
  when: tfenv_stat.stat.exists

# Customize Per existing user
- name : list users to apply tfenv
  shell: |
    getent passwd | awk -F: '$3 > 999 {print $1}'
  register: users

- debug:
    var: users
    verbosity: 2

- name: Create user bin directory
  file: path=/home/{{ item }}/.local/bin/ state=directory mode="a+rw"
  when: tfenv_stat.stat.exists
  with_items: "{{ users.stdout_lines }}"

- name: Configure tfenv on user bin.
  file:
    src: "/opt/tfenv/bin/tfenv"
    dest: "/home/{{ item }}/.local/bin/tfenv"
    state: link
  with_items: "{{ users.stdout_lines }}"
  when: tfenv_stat.stat.exists

- name: update tfenv on bash_profile
  lineinfile:
    dest: /home/{{ item }}/.bash_profile
    state: present
    line: 'export PATH="/opt/tfenv/bin/:$PATH"'
  with_items: "{{ users.stdout_lines }}"

# Check status
- shell: bash -ilc 'which tfenv'
  register: which_tfenv
  failed_when: false
  changed_when: false

- debug:
    var:  which_tfenv.stdout
    verbosity: 2

- command: tfenv -v
  register: result_tfenv
  failed_when: false
  changed_when: false

- debug:
    var: result_tfenv.stdout
  